### ISSUE TITLE
Error building with `make`

### ISSUE THREAD

**Issue by Madour** [MiguelMJ/Candle#2]
OS : Linux Manjaro

Tried to compile using the Makefile :

`make prep` 
-> debug/demo.d : File does not exist

then I try `make`, the file debug/demo.d is created but I get an error at "checking debug dependencies for demo.cpp"

I believe demo.d is causing the errors, here is what it contains : 

```
debug/demo.o: demo.cpp include/Candle/Lighting.hpp \
 include/Candle/Util.hpp include/Candle/LightSource.hpp
\t$(call print_info,Building $@)
\t$(CXX) -c $(CXXFLAGS) $(DBGCFLAGS) -o $@ $<
```
The other .d files have the same last 2 lines I have no idea if this is the expected output or not (but it looks strange to me).

**Comment by MiguelMJ** [comment]
The problem was that the makefile tried to include the generated dependency files before even creating the needed directories. Now it should work.

**Comment by MiguelMJ** [comment]
@all-contributors please add @Madour for bug and infra
