### ISSUE TITLE
setColor on RadialLight doesn't change color

### ISSUE THREAD

**Issue by EOSource** [MiguelMJ/Candle#31]
So have got all my RadialLight's working like normal but when using .setColor say sf::color::red for example, there is no change in the light color at all? but examples shows it works?

This is compiled with static SFML with /MT option enabled.

Also had an exit error where candle gives an access violation when you exit program which i fixed by manually calling the destructor for RadialLight on every single one made.

Compiled using Visual C++ 2019, /MT

**Comment by MiguelMJ** [comment]
`.setbeamcolor` is not a Candle function... Do you mean [.setColor](https://miguelmj.github.io/Candle/classcandle_1_1LightSource.html#ad4ad5b2a1bee472465cf5e45799a26dc)`?

And could you show a capture of the error you get on exit, please?
Thanks!

**Comment by EOSource** [comment]
![image](https://user-images.githubusercontent.com/92658171/140834324-ca6703e8-b9b1-4368-99c8-7b740fb3ab5e.png)
That is the error i get on exit if i dont call the deconstructor manually on every object before exiting the with either window.close() or WM_QUIT or std::exit(0) then i get that error in image.

Also, yes it is actually .setColor my bad

**Comment by MiguelMJ** [comment]
Ok, I see there's now #32 for that last thing.
About the color not changing: There's only a reason I can think of (based on the code you showed on that issue). You are drawing the lights to a LightingArea in fog mode, but not drawing them afterwards to the scene.
When you draw to a fog area, the opacity is eliminated where the light is, but nothing else, there is no color added. If you want a light both to eliminate the fog _and_ produce some color, then you have to draw it twice: one in the fog and one in the scene.
Let me know if that was the problem
Thank you!

**Comment by EOSource** [comment]
Hi thank you for responding, and can confirm after doing this:
![image](https://user-images.githubusercontent.com/92658171/141283510-665b75c5-552b-4699-8ee6-998e36cc3338.png)

its now working and i get color yay!! you might want to add a huge TIP to your tutorial docs when using .setcolor and fog
![image](https://user-images.githubusercontent.com/92658171/141283625-3c3b7271-59b4-4532-86da-b05e23f28541.png)

**Comment by MiguelMJ** [comment]
Thank you for the feedback! ❤️ 
I remember mentioning it briefly in the fog tutorial, but I'll do it too in the .setColor description too.
Closing this ;)
