### ISSUE TITLE
Shadow display error

### ISSUE THREAD

**Issue by zzc-1024** [MiguelMJ/Candle#35]
# Environment
Windows11
VS2022
SFML-2.5.1 
Candle-1.0.2
set(SFML_STATIC_LIBRARIES TRUE)
# Screenshot
![image](https://user-images.githubusercontent.com/67462033/205480453-5e41d02c-60bf-43af-9dde-fa7770d245ca.png)

**Comment by MiguelMJ** [comment]
Hello @zzc-1024, thanks for reporting!
This is actually a known issue, explained in the documentation ([here](https://miguelmj.github.io/Candle/lights_shadows.html#autotoc_md9)).

To solve it, you must avoid intersecting segments.

![example of usage](https://user-images.githubusercontent.com/37369782/205592219-55c1e852-157a-46d0-bc4e-240600891ef1.png)

In this image you have an example of a problematic intersection (case 1) and an alternative but equivalent layout of segments that work the same way (case 2).

I hope it helps, don't hesitate to ask anything!
