### ISSUE TITLE
candle::RadialLight has an offset origin point

### ISSUE THREAD

**Issue by chu65536** [MiguelMJ/Candle#37]
For some reason RadialLight has an offset origin. It mean that even setting origin to (0, 0) breaks everything which makes no sense to me

```c++
    // ...
    const float BASE_RADIUS = 400.0f;
    // ...
    RadialLight::RadialLight()
        : LightSource()
        {
        if(!l_texturesReady){
            // The first time we create a RadialLight, we must create the textures
            initializeTextures();
            l_texturesReady = true;
        }
        m_polygon.setPrimitiveType(sf::TriangleFan);
        m_polygon.resize(6);
        m_polygon[0].position =
        m_polygon[0].texCoords = {BASE_RADIUS+1, BASE_RADIUS+1};
        m_polygon[1].position =
        m_polygon[5].position =
        m_polygon[1].texCoords =
        m_polygon[5].texCoords = {0.f, 0.f};
        m_polygon[2].position =
        m_polygon[2].texCoords = {BASE_RADIUS*2 + 2, 0.f};
        m_polygon[3].position =
        m_polygon[3].texCoords = {BASE_RADIUS*2 + 2, BASE_RADIUS*2 + 2};
        m_polygon[4].position =
        m_polygon[4].texCoords = {0.f, BASE_RADIUS*2 + 2};
        Transformable::setOrigin(BASE_RADIUS, BASE_RADIUS);
        setRange(1.0f);
        setBeamAngle(360.f);
        // castLight();
        s_instanceCount++;
    }
```

**Comment by MiguelMJ** [comment]
Hello @chu65536 !
Are you having any specific trouble with this? What is the use case where you need to change the transform origin of a light source instead of the position?

**Comment by chu65536** [comment]
I think it would be nice to make this moment more intuitive. But I understand perfectly well that it already works in most cases and may not be worth the effort. In short, the problem can probably be closed

**Comment by MiguelMJ** [comment]
Tbh, this project is now a bit old and I'm aware there are lots of pending improvements and updates. I've created a new issue (#38) to tackle a new release any moment in the future... I just hope for now is at least somehow useful. 
Thanks for the feedback!
